apiVersion: v2
appVersion: "8.4.5-2.1.7"
name: mysql-operator
description: MySQL Operator Helm Chart for deploying MySQL InnoDB Cluster in Kubernetes
type: application
version: "2.1.7"
icon: https://www.mysql.com/common/logos/logo-mysql-170x115.png
